server:
  port: 8072

spring:
  application:
    name: "api-gateway"
  profiles:
    active: "@spring.profiles.active@"

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

logging:
  level:
    com:
      goaleaf:
        gateway: DEBUG